### ISSUE TITLE
Sick Feedback section 

### ISSUE THREAD

**Issue by ikirtivardhansingh** [ikirtivardhansingh/portfolio#18]
The feedback section should be in a white box and aligned right side of the page. 
The input box should also be aligned in a line. 
Find the web page [here](https://ikirtivardhansingh.github.io/Transformation_in_Computational_Linguistics_with_Sanskrit_A_Brand_New_Approach_to_NLP.html).
![image](https://user-images.githubusercontent.com/40534936/120027152-a7134600-c010-11eb-90fd-83aa2beb2f2b.png)

**Comment by ChhaviArora1401** [comment]
I'd like to fix it.

**Comment by ikirtivardhansingh** [comment]
> I'd like to fix it.
Sure @ChhaviArora1401, go ahead!
